package com.b1nd.dodamdodam.nightstudy.domain.nightstudy.exception

import com.b1nd.dodamdodam.core.common.exception.BasicException

class NightStudyNotFoundException: BasicException(NightStudyExceptionCode.NIGHT_STUDY_NOT_FOUND)

class NightStudyBannedException: BasicException(NightStudyExceptionCode.NIGHT_STUDY_BANNED)

class NotMyNightStudyException: BasicException(NightStudyExceptionCode.NOT_MY_NIGHT_STUDY)

class NotLeaderException: BasicException(NightStudyExceptionCode.NOT_LEADER)

class PeriodOverlappedException: BasicException(NightStudyExceptionCode.PERIOD_OVERLAPPED)

class BanNotFoundException: BasicException(NightStudyExceptionCode.BAN_NOT_FOUND)

class AlreadyBannedException: BasicException(NightStudyExceptionCode.ALREADY_BANNED)

class NotProjectNightStudyException: BasicException(NightStudyExceptionCode.NOT_PROJECT_NIGHT_STUDY)

class RoomAlreadyAssignedException: BasicException(NightStudyExceptionCode.ROOM_ALREADY_ASSIGNED)

class AlreadyApprovedException: BasicException(NightStudyExceptionCode.ALREADY_APPROVED)

class InvalidNightStudyTypeException: BasicException(NightStudyExceptionCode.INVALID_NIGHT_STUDY_TYPE)

class NightStudyTeamNotFound: BasicException(NightStudyExceptionCode.TEAM_NOT_FOUND)

class NightStudyNotTeamOwnerException: BasicException(NightStudyExceptionCode.NOT_TEAM_OWNER)

class NightStudyTeamInviteeNotFoundException: BasicException(NightStudyExceptionCode.TEAM_INVITEE_NOT_FOUND)

class NightStudyTeamInvitationNotReceivedException: BasicException(NightStudyExceptionCode.TEAM_INVITATION_NOT_RECEIVED)

class AlreadyJoinedTeamException: BasicException(NightStudyExceptionCode.ALREADY_JOINED_TEAM)

class NotJoinedTeamException: BasicException(NightStudyExceptionCode.NOT_JOINED_TEAM)