spring:
  r2dbc:
    url: r2dbc:${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    url: jdbc:${MYSQL_HOST}
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    validate-on-migrate: false

grpc:
  client:
    service-auth:
      address: 'static://localhost:9092'
      negotiation-type: plaintext
