name: CD Production

on:
  push:
    tags:
      - 'v*'

jobs:
  detect:
    uses: ./.github/workflows/cd-production-detect.yml

  build:
    needs: detect
    if: needs.detect.outputs.has_services == 'true'
    strategy:
      max-parallel: 2
      matrix:
        service: ${{ fromJSON(needs.detect.outputs.services) }}
    uses: ./.github/workflows/cd-production-build.yml
    with:
      service: ${{ matrix.service }}
      tag: ${{ needs.detect.outputs.tag }}
    secrets: inherit

  deploy:
    needs: [detect, build]
    if: always() && needs.detect.outputs.has_services == 'true' && (needs.build.result == 'success')
    uses: ./.github/workflows/cd-production-deploy.yml
    with:
      services: ${{ needs.detect.outputs.services }}
      tag: ${{ needs.detect.outputs.tag }}
      k8s_repository: Team-B1ND/dodamdodam-k8s
    secrets: inherit
